export const MINE_BLOCK_BEGIN = 'MINE_BLOCK_BEGIN';
export const MINE_BLOCK_SUCCESS = 'MINE_BLOCK_SUCCESS';
export const MINE_BLOCK_ERROR = 'MINE_BLOCK_ERROR';
export const MINE_BLOCK_CLOSE_SNACK = 'MINE_BLOCK_CLOSE_SNACK';
//
export const GET_CHAIN_BEGIN = 'GET_CHAIN_BEGIN';
export const GET_CHAIN_SUCCESS = 'GET_CHAIN_SUCCESS';
export const GET_CHAIN_ERROR= 'GET_CHAIN_ERROR';
//
export const POST_TRANSACTION_BEGIN = 'POST_TRANSACTION_BEGIN';
export const POST_TRANSACTION_SUCCESS = 'POST_TRANSACTION_SUCCESS';
export const POST_TRANSACTION_ERROR = 'POST_TRANSACTION_ERROR';
export const POST_TRANSACTION_CLOSE_SNACK = 'POST_TRANSACTION_CLOSE_SNACK';